Repository MehrShahbaz/happy-beans, pull requests merged in 2025-08, with the labels that each got.

#2 Feature/mehrshahbaz user auth
  .env.sample
  .github/workflows/pr-build.yml
  .gitignore
  src/main/kotlin/happybeans/config/DataInitializer.kt
  src/main/kotlin/happybeans/config/DotenvConfig.kt
  src/main/kotlin/happybeans/config/WebConfig.kt
  src/main/kotlin/happybeans/config/advice/GlobalExceptionHandler.kt
  src/main/kotlin/happybeans/config/argumentResolver/LoginMemberArgumentResolver.kt
  src/main/kotlin/happybeans/config/interceptor/AdminInterceptor.kt
  src/main/kotlin/happybeans/config/interceptor/BaseAuthInterceptor.kt
  src/main/kotlin/happybeans/config/interceptor/MemberInterceptor.kt
  src/main/kotlin/happybeans/config/interceptor/RestaurantOwnerInterceptor.kt
  src/main/kotlin/happybeans/controller/HelloWorldController.kt
  src/main/kotlin/happybeans/dto/auth/AuthTokenPayload.kt
  src/main/kotlin/happybeans/dto/error/ErrorResponse.kt
  src/main/kotlin/happybeans/enums/UserRole.kt
  src/main/kotlin/happybeans/infrastructure/JwtProvider.kt
  src/main/kotlin/happybeans/model/User.kt
  src/main/kotlin/happybeans/repository/UserRepository.kt
  src/main/kotlin/happybeans/utils/annotations/LoginMember.kt
  src/main/kotlin/happybeans/utils/exception/EntityNotFoundException.kt
  src/main/kotlin/happybeans/utils/exception/UnauthorisedUserException.kt
  src/main/resources/application.properties
  src/test/kotlin/com/example/happybeans/HappyBeansApplicationTests.kt
  src/test/kotlin/happybeans/config/argumentResolver/LoginMemberArgumentResolverTest.kt
  src/test/kotlin/happybeans/config/interceptor/AdminInterceptorTest.kt
  src/test/kotlin/happybeans/config/interceptor/MemberInterceptorTest.kt
  src/test/kotlin/happybeans/config/interceptor/RestaurantOwnerInterceptorTest.kt
  src/test/kotlin/happybeans/infrastructure/JwtProviderTest.kt
  src/test/kotlin/happybeans/repository/UserRepositoryTest.kt
Labels: enhancement

#4 docs: Add comprehensive development documentation and templates
  docs/commit_template.md
  docs/dev_docs.md
  docs/pull_request_template.md
Labels: documentation

#17 Feature: Setup db Postgres
  .env.sample
  build.gradle.kts
  docs/setup_database.md
  src/main/kotlin/happybeans/Application.kt
  src/main/kotlin/happybeans/config/DotenvConfig.kt
  src/main/resources/application.properties
Labels: enhancement

#15 Feature: Stripe payment
  build.gradle.kts
  src/main/kotlin/happybeans/config/DataInitializer.kt
  src/main/kotlin/happybeans/config/StripeConfig.kt
  src/main/kotlin/happybeans/controller/guest/GuestDishController.kt
  src/main/kotlin/happybeans/controller/member/MemberOrderController.kt
  src/main/kotlin/happybeans/controller/payment/WebhookController.kt
  src/main/kotlin/happybeans/dto/dish/DishOptionCreateRequest.kt
  src/main/kotlin/happybeans/dto/order/OrderIntentResponse.kt
  src/main/kotlin/happybeans/dto/stripe/StripeEventDto.kt
  src/main/kotlin/happybeans/enums/PaymentStatus.kt
  src/main/kotlin/happybeans/model/Dish.kt
  src/main/kotlin/happybeans/model/Order.kt
  src/main/kotlin/happybeans/model/OrderProduct.kt
  src/main/kotlin/happybeans/model/Payment.kt
  src/main/kotlin/happybeans/model/Restaurant.kt
  src/main/kotlin/happybeans/model/User.kt
  src/main/kotlin/happybeans/repository/PaymentRepository.kt
  src/main/kotlin/happybeans/service/DishService.kt
  src/main/kotlin/happybeans/service/EmailDispatchService.kt
  src/main/kotlin/happybeans/service/MemberAuthService.kt
  src/main/kotlin/happybeans/service/MemberOrderService.kt
  src/main/kotlin/happybeans/service/OrderPaymentService.kt
  src/main/kotlin/happybeans/service/PaymentService.kt
  src/main/kotlin/happybeans/service/RestaurantService.kt
  src/main/kotlin/happybeans/service/StripePaymentService.kt
  src/main/resources/application.properties
  src/main/resources/static/payment-failed.html
  src/main/resources/static/payment-success.html
  src/test/kotlin/happybeans/controller/admin/AdminJoinRequestControllerTest.kt
  src/test/kotlin/happybeans/controller/member/MemberOrderControllerTest.kt
  src/test/kotlin/happybeans/service/AdminUserServiceTest.kt
  src/test/kotlin/happybeans/service/EmailDispatchServiceTest.kt
  src/test/kotlin/happybeans/service/PaymentServiceTest.kt
  src/test/resources/application.properties
Labels: In Progress
